package quanlysach;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlysach.DSSach;
import quanlysach.Sach;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author s
 */
public class GiaodienSach extends javax.swing.JFrame {
    public DSSach ds= new DSSach();
    boolean flag = true;
    /**
     * Creates new form GiaodienSach
     */
    public GiaodienSach() {
        initComponents();
        TaoTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ttma = new javax.swing.JTextField();
        ttten = new javax.swing.JTextField();
        ttgia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tacgia = new javax.swing.JTextField();
        NXB = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bang = new javax.swing.JTable();
        Them = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        Sua = new javax.swing.JButton();
        Luu = new javax.swing.JButton();
        Timkiem = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Thoat = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thông tin sách");

        jLabel2.setText("Ma Sach");

        jLabel3.setText("Ten Sach");

        jLabel4.setText("Gia");

        ttma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttmaActionPerformed(evt);
            }
        });

        ttten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tttenActionPerformed(evt);
            }
        });

        jLabel5.setText("Tac gia");

        jLabel6.setText("Nha xuat ban");

        bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ma Sach", "Ten Sach", "Tac gia", "Nha xuat ban", "Gia"
            }
        ));
        bang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bang);

        Them.setText("Them");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Xoa.setText("Xoa");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        Sua.setText("Sua");
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });

        Luu.setText("Luu");
        Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuuActionPerformed(evt);
            }
        });

        Timkiem.setText("Tim kiem");
        Timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimkiemActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Thoat.setText("Thoat");
        Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ttten, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                            .addComponent(ttgia)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ttma, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NXB, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(tacgia)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Them)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Xoa)
                                .addGap(18, 18, 18)
                                .addComponent(Sua)
                                .addGap(18, 18, 18)
                                .addComponent(Luu)
                                .addGap(18, 18, 18)
                                .addComponent(Timkiem)
                                .addGap(26, 26, 26)
                                .addComponent(Clear)
                                .addGap(18, 18, 18)
                                .addComponent(Thoat)))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ttma, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(tacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ttten, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ttgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Them)
                    .addComponent(Xoa)
                    .addComponent(Sua)
                    .addComponent(Luu)
                    .addComponent(Timkiem)
                    .addComponent(Clear)
                    .addComponent(Thoat))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel tbModelTT;
    public void TaoTable()
    {
        tbModelTT = new DefaultTableModel();
        String tieude[] = {"Ma sach", "Ten sach", "Gia","Tac gia","Nha xuat ban"};
        tbModelTT.setColumnIdentifiers(tieude);
        bang.setModel(tbModelTT);
        setVisible(true);
    }
    private void tttenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tttenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tttenActionPerformed
    String row [] = new String [5];
    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        /*String MaSach = ttma.getText();
        String TenSach = ttten.getText();
        int Gia = Integer.parseInt(ttgia.getText());
        String Tacgia = tacgia.getText();
        String NXBan = NXB.getText();*/
    
        row[0] = ttma.getText();
        row[1] = ttten.getText();
        row[2] = ttgia.getText().toString();
        row[3] = tacgia.getText();
        row[4] = NXB.getText();
        Sach S = new Sach(row[0],row[1],Integer.parseInt(row[2]),row[3],row[4]);
        
        boolean a = ds.checkID(ttma.getText());
        if(a)
        {
            ds.getDs().add(S);
            tbModelTT.addRow(row);
        }
        else
            JOptionPane.showMessageDialog(this, "trung ma sach");

        setrong();
       
        // TODO add your handling code here:
    }//GEN-LAST:event_ThemActionPerformed

    private void ttmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttmaActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        //if (bang.getSelectedRow()== -1 )
        //    JOptionPane.showMessageDialog(this, "chua chon dong muon xoa");
        ds.xoaSach(bang.getSelectedRow());
        tbModelTT.removeRow(bang.getSelectedRow());
        bang.selectAll();
        setrong();
    }//GEN-LAST:event_XoaActionPerformed
    private void setrong(){
        ttma.setText("");
        ttten.setText("");
        ttgia.setText("");
        tacgia.setText("");
        NXB.setText("");
    }
    private void TimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimkiemActionPerformed
        String a = ttma.getText();
        boolean b = ds.checkID(a);
        if (b==false) {
            ttten.setText(ds.timsach(a).getTenSach());    
            ttgia.setText(String.valueOf(ds.timsach(a).getGia()));
            tacgia.setText(ds.timsach(a).getTacgia());
            NXB.setText(ds.timsach(a).getNhaxuatban());
        }
        else{
            JOptionPane.showMessageDialog(this, "khong co sach nay");
        }
    }//GEN-LAST:event_TimkiemActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        setrong();
    }//GEN-LAST:event_ClearActionPerformed
    public void readfile(){
        try{
            FileReader fr = new FileReader ("data.txt");
            BufferedReader br= new BufferedReader(fr);
            String line="";
            while (true){
                line=br.readLine();
                if (line==null)
                    break;
                String txt[]=line.split(";");
                String ma = txt[0];
                String ten = txt[1];
                String gia = txt[2];
                String tacgia = txt[3];
                String nxb = txt[4];
                ds.getDs().add(new Sach(ma,ten,Integer.parseInt(gia),tacgia,nxb));
                tbModelTT.addRow(txt);
            }
        } catch(Exception e){
            
        }
    }
    
    private void LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuuActionPerformed
        String chuoi;
        if (flag==true)
            readfile();
        flag=false;
        try{
            //Here true is to append the content to file
        FileWriter fw = new FileWriter("data.txt");
        //BufferedWriter writer give better performance
        
        BufferedWriter bw = new BufferedWriter(fw);
        for(int i=0;i<ds.getDs().size();i++){
            chuoi=ds.getDs().get(i).getMaSach()+";"+ds.getDs().get(i).getTenSach()+";"+ds.getDs().get(i).getGia()+";"+ds.getDs().get(i).getTacgia()+";"+ds.getDs().get(i).getNhaxuatban();
            bw.write(chuoi);
            bw.newLine();
        }
        
        bw.close();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_LuuActionPerformed

    private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatActionPerformed
        int ret = JOptionPane.showConfirmDialog(null,"Ban co muon thoat","Thoat",JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_ThoatActionPerformed

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
            int index = bang.getSelectedRow();
           row[0] = ttma.getText();
           row[1] = ttten.getText();
           row[2] = ttgia.getText().toString();
           row[3] = tacgia.getText();
           row[4] = NXB.getText();
           ds.xoaSach(index);
           tbModelTT.removeRow(index);
           ds.getDs().add(index, new Sach(row[0],row[1],Integer.parseInt(row[2]),row[3],row[4]));
           tbModelTT.insertRow(index, row);
           //tbModelTT.moveRow(index,ds.getDs().size(),(ds.getDs().size()-index));
           
    }//GEN-LAST:event_SuaActionPerformed

    private void bangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangMouseClicked
       int a = bang.getSelectedRow();
       if (a!=-1){
           ttma.setText(ds.getDs().get(a).getMaSach());
           ttten.setText(ds.getDs().get(a).getTenSach());
           ttgia.setText(String.valueOf(ds.getDs().get(a).getGia()));
           tacgia.setText(ds.getDs().get(a).getTacgia());
           NXB.setText(ds.getDs().get(a).getNhaxuatban());
       }
        
    }//GEN-LAST:event_bangMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaodienSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaodienSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaodienSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaodienSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaodienSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Luu;
    private javax.swing.JTextField NXB;
    private javax.swing.JButton Sua;
    private javax.swing.JButton Them;
    private javax.swing.JButton Thoat;
    private javax.swing.JButton Timkiem;
    private javax.swing.JButton Xoa;
    private javax.swing.JTable bang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tacgia;
    private javax.swing.JTextField ttgia;
    private javax.swing.JTextField ttma;
    private javax.swing.JTextField ttten;
    // End of variables declaration//GEN-END:variables
}
